import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { getSession, signIn, useSession } from "next-auth/react";
import styles from "../styles/Home.module.css";
import Router from "next/router";
import { FormEventHandler, useState } from "react";

const Home: NextPage = ({ restaurants }: any) => {

  const { data: session } = useSession();

  console.log('session is', session)
  console.log('restaurants is', restaurants)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Hello {session?.user?.email}</div>
        {restaurants.length > 0 && (<div>
          <p>Your restaurants:</p>
          <div>
            {restaurants.map((restaurant: any) => (
              <p key={restaurant['id']}>{restaurant['name']}</p>
            ))}
          </div>
        </div>)}

      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export async function getServerSideProps({ req }: any) {
  let session = await getSession({ req });
  let restaurants = await fetch(`${process.env.NEXT_API_URL}restaurants`, req)
  let restaurantsResult = await restaurants.json();

  console.log('restaurantsResult is', restaurantsResult)

  if (!session) {
    return {
      redirect: {
        destination: '/auth/signin',
        permanent: false
      }
    }
  }

  return {
    props: {
      session,
      restaurants: restaurantsResult.apiResult
    }
  }

}

export default Home;
