import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { getSession, signIn, useSession } from "next-auth/react";
import styles from "../styles/Home.module.css";
import Router from "next/router";
import { FormEventHandler, useState } from "react";

const Home: NextPage = () => {

  const { data: session } = useSession();

  console.log('session is', session)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Hello {session?.user?.email}</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export async function getServerSideProps({ req }: any) {
  let session = await getSession({ req });
  console.log('req session is', session)
  if (!session) {
    return {
      redirect: {
        destination: '/auth/signin',
        permanent: false
      }
    }
  }

  return {
    props: { session }
  }

}

export default Home;
